name: CI-CD-GitOps-Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'cicd/my-app-gitops/helm-chart/values.yaml'
  workflow_dispatch:

env:
  IMAGE_NAME: myapp
  ECR_REPO: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/myapp
  TAG: ${{ github.sha }}

jobs:

# SAST
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3

# Secret Scan
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2

# Dependency Scan
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

# IaC Scan
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@master
        with:
          directory: .

# Build + Push + Scan + GitOps Update
  build-and-gitops:
    runs-on: ubuntu-latest
    needs: [sast, secret-scan, dependency-scan, iac-scan]

    steps:
      - uses: actions/checkout@v4

      # Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # AWS Auth
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE }}

      # Login ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build locally
      - name: Build Image (local)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
          # Push to ECR
      - name: Tag & Push Image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.ECR_REPO }}:${{ env.TAG }}
          docker push ${{ env.ECR_REPO }}:${{ env.TAG }}

      # Scan Image
      - name: Scan Image
        id: scan
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ env.ECR_REPO }}:${{ env.TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1

      # Delete if vulnerable
      - name: Delete Vulnerable Image
        if: steps.scan.outcome == 'failure'
        run: |
          echo "Deleting vulnerable image..."
          aws ecr batch-delete-image \
            --repository-name myapp \
            --image-ids imageTag=${{ env.TAG }}
          exit 1

      # Setup Helm (for templating only)
      - name: Setup Helm
        uses: azure/setup-helm@v4

      # Helm Lint 
      - name: Helm Lint
        run: |
          helm lint cicd/my-app-gitops/helm-chart
      - name: Helm Template Test
        run: |
          helm template my-app cicd/my-app-gitops/helm-chart

      # Update Helm values.yaml (GitOps step)
      - name: Install yq
        run: |
            sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
            sudo chmod +x /usr/local/bin/yq

      - name: Update values.yaml safely
        run: |
            yq -i ".image.tag = \"${{ env.TAG }}\"" cicd/my-app-gitops/helm-chart/values.yaml
      - name: Setup Git Auth
        run: |
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/abani-rautray/my-app-gitops.git

      # Commit & Push changes (trigger ArgoCD)
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add cicd/my-app-gitops/helm-chart/values.yaml
          git commit -m "Update image tag to ${{ env.TAG }}" || echo "No changes"
          git push

# DAST (after deployment by ArgoCD)
  dast:
    runs-on: ubuntu-latest
    needs: build-and-gitops
    steps:
      - name: Run ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "https://your-staging-app.com"